# Generated by Django 6.0.3 on 2026-03-19 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemed', '0002_alter_image_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessinglog',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['study'], name='telemed_ima_study_i_1af854_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_by', '-created_at'], name='telemed_ima_created_662368_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created_at'], name='telemed_ima_created_7537a6_idx'),
        ),
        migrations.AddIndex(
            model_name='imageprocessinglog',
            index=models.Index(fields=['user', '-processed_at'], name='telemed_ima_user_id_f39848_idx'),
        ),
        migrations.AddIndex(
            model_name='imageprocessinglog',
            index=models.Index(fields=['image'], name='telemed_ima_image_i_9c647d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_by', '-created_at'], name='telemed_pat_created_db33d8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='telemed_pat_patient_d81b34_idx'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['patient'], name='telemed_stu_patient_5bd222_idx'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['created_by', '-created_at'], name='telemed_stu_created_b9b9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['-created_at'], name='telemed_stu_created_2000a5_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='telemed_use_user_id_1b3f74_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['quota_reset_date'], name='telemed_use_quota_r_97203d_idx'),
        ),
    ]
