# Generated by Django 6.0.3 on 2026-03-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemed', '0004_encryptionkey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='encryptionkey',
            new_name='telemed_enc_image_i_21fca1_idx',
            old_name='telemed_enc_image_id_idx',
        ),
        migrations.RenameIndex(
            model_name='encryptionkey',
            new_name='telemed_enc_sha256__04bebd_idx',
            old_name='telemed_enc_sha256_idx',
        ),
        migrations.AlterField(
            model_name='encryptionkey',
            name='mode',
            field=models.CharField(choices=[('itied', 'ITIED (DNA-Chaos, Legacy)'), ('itiedc', 'ITIEDC (DNA-Chaos Compression, Legacy)'), ('aes_gcm_zstd', 'AES-256-GCM + zstandard (Recommended)')], default='aes_gcm_zstd', help_text='Encryption mode used', max_length=15),
        ),
    ]
